added test framework, cleaned up map files

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -12,6 +12,14 @@ then
     exit 1
 fi
 
+./node_modules/.bin/tsc -p ./tests
+rval=$?
+if [ $rval -ne 0 ];
+then
+    echo "tsc failed (error code: $rval)"
+    exit 3
+fi
+
 ./node_modules/.bin/webpack
 rval=$?
 if [ $rval -ne 0 ];
